title: Nevzat Çırak (nevzatcirak)
description: Software Engineer
author:
  name: Nevzat Çırak
  nickname: nevzatcirak
  twitter: nevzatcirak
hostname: nevzatcirak.github.io # used to determine if google analytics should be triggered
url: https://nevzatcirak.github.io # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:title/

# stuff for jekyll-seo-tag
social:
  name: Nevzat Çırak
  links:
    - https://twitter.com/nevzatcirak
    - https://github.com/nevzatcirak
    - https://nevzatcirak.me/
    - http://www.linkedin.com/in/nevzatcirak

twitter:
  username: nevzatcirak

# main page content
email: 
  value: nevzatcirak17@gmail.com
  class: fa fa-envelope

links:
  - name: github
    url: https://github.com/nevzatcirak
    class: fab fa-github
  - name: twitter
    url: https://twitter.com/nevzatcirak
    class: fab fa-twitter
  - name: personal website
    url: https://nevzatcirak.me/
    class: far fa-newspaper
  - name: linkedin
    url: https://www.linkedin.com/in/nevzatcirak
    class: fab fa-linkedin-in
  - name: cv (pdf)
    id: resume
    type: download
    url: https://nevzatcirak.me/cv
    class: fas fa-file-alt

# additional stuff
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
